### PR TITLE
Homepage first version

### PR DESCRIPTION
**Pull request by jfranciscosousa**
Contains the homepage earlier designed. 
Also changes the `gatsby` framework with `next.js` because the second one has better compatibility with IPFS.

### CODE REVIEW

**Comment by jfranciscosousa** [comment]
@VictorBjelkholm your Jenkins environment needs `libpng-dev` for image assets optimization, could you add that when you can please?

**Comment by VictorBjelkholm** [comment]
Got it to work and it's renders now, see https://ipfs.io/ipfs/QmckNzmqVhAUvTHLKQVf4N9mDfSem3z4PFHCd8i56xU8Jx

I leave the actual review of the website for @flyingzumwalt and @mgoelzer though.

**Comment by jfranciscosousa** [comment]
Many thanks, everything seems to be working as expected.

However the design should be reviewed instead of this particular website, we are going to implement it when it gets validated by you guys, we only developed the homepage to get the components and the base styles all set up.

**Comment by diasdavid** [comment]
I'm getting things a bit more tidy (context here - https://github.com/ipfs/conf/issues/41) merging this one to move the entire work to another repo.

**Pull request merged**
