### PR TITLE
Add Jenkinsfile and Makefile

### PR DESCRIPTION
**Pull request by VictorBjelkholm**
Adds a Jenkinsfile which does Previews for the PRs and deploys when master changes.

Add Makefile which the jenkins pipeline uses to do the build.

Removed `gh-pages -d public` as that's not how we'll be doing deploys. Haven't removed it from the list of modules in `package.json` though as I didn't look if it's being used elsewhere.

### CODE REVIEW

**Comment by VictorBjelkholm** [comment]
@jfranciscosousa good idea, added in the Makefile.

So, in it's current state, this PR now has a rendered preview, it's how the website will look once this PR is merged to master, built and added to IPFS. 

image

Clicking on the "Details" takes you to the actual website so you can inspect it closer without having to build it yourself.

Once merged, `master` will start getting auto-deployed to `conf.ipfs.io`, as soon as changes there happens. So make sure you review PRs as once they get merged to master, they get deployed.

**Comment by jfranciscosousa** [comment]
Similar to our in house flows, we got it. 

Just one problem though. In IPFS we have to deal with the `pathPrefixes`. Our static site generator assumes we deploy at the root of a path, like `conf.ipfs.io` but in this case we have the `/ipfs/Qmbt4FqBiGCFhRt8b1MsS4rsfd5PLNRy7w4rdLFyqHP2z3/` prefix. This is probably different each time we publish right? A solution could be using something `pathPrefix: process.env.PATH_PREFIX` on `gatsby-config.js`, and supplying that prefix via the environment variable during the build process. Our `build` task on our `package.json` would then use the flag `--prefix-paths`.

**Comment by VictorBjelkholm** [comment]
@jfranciscosousa the prefix you mention there (`/ipfs/Qmbt4FqBiGCFhRt8b1MsS4rsfd5PLNRy7w4rdLFyqHP2z3/`) will change as the website changes. The website will be accessible on probably these variations: `conf.ipfs.io`, `localhost:X` (for dev I assume), `ipfs.io/ipfs/$HASH` and others. 

What you have to do is to always load resources relative to your current path. So we shouldn't have to specify the root, the root should just be `.` basically.

**Comment by jfranciscosousa** [comment]
Ok, got it, we'll fix that as soon as we can. Thanks :raised_hands:

**Comment by luisptorres** [comment]
Hi @VictorBjelkholm we changed from gatsby to next.js in order to solve the relative paths issue, but it doesn't change anything to you.

In order to make that change, we need permissions so we can open PRs to your repo. Alternatively, we can continue development in our repository and you clone it in the end.

**Comment by VictorBjelkholm** [comment]
The permission problem has been solved.

@luisptorres @jfranciscosousa any updates if you managed to get relative paths to work correctly for the different ways the website can be loaded?

**Comment by luisptorres** [comment]
@VictorBjelkholm Thanks. Yes, we got that working.

**Comment by VictorBjelkholm** [comment]
@luisptorres can you push the changes and make a PR so we can try it out?

**Comment by jfranciscosousa** [comment]
@VictorBjelkholm on it, will open a PR with the first version of the homepage design.

**Pull request closed without merging**
